version: "3"
services:
  api:
    build: .
    ports:
      - "8080:8080"
    volumes:
      - .:/go/src/app
    environment:
      - PORT=8080
      - DB_HOST=db
      - DB_USER=root
      - DB_PASSWORD=root
      - DB_NAME=phinance
    depends_on:
      - db
  db:
    image: postgres:11.2-alpine
    ports:
      - "5432:5432"
    environment:
      - POSTGRES_USER=root
      - POSTGRES_PASSWORD=root
      - POSTGRES_DB=phinance
    volumes:
      - ./db/init.sql:/docker-entrypoint-initdb.d/init.sql
